name: The Source of All Wonders
favicon: null
layout_spectrum: 0
typography_spectrum: 0.06275140028446913
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#719ac6'
    - '#e1e4e9'
    - '#1b170b'
    - '#c3b89a'
    - '#4e4830'
  brandStrength: 0.25
  lightness: 0.3447236376814544
  saturation: 0.2634472642093897
  rhythmicContrast: 0.75
purpose: []
